# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.0

jobs:
  display_branch:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: echo $CIRCLE_BRANCH
  pr:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "3b:c2:4c:31:fa:a6:f5:6b:2e:90:b5:19:ea:c0:ee:de"
            - "31:89:4b:a7:c7:d9:42:4e:bc:9b:bf:39:3b:df:67:21"
      - run: |
          echo '104.154.99.4 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw5AjaS6bU+BxtOvbbSwx3pC0GcJmKaCkYep2WUSSL1vcwyyFBVwdukTP18ysj6huuxnMWNwPLqJSWT4jI6cbUZWf7bWVRFIZJ+0JXv3pRfJKT+mOLk4xhPHvt5idh4rU63dJRJjLodJpaS48gfTdPxt4KZPm/Y76KCDAMD++K0Itd9G/Aily7miaPXTBcx7ioobwhRBiJxJSyQoSolXrIpN7dgw7Kih1HLIsAj+iChHOtL7NCsK8+xYrUCCdAH/7ldKz4opgx+FY3tTHrgvZtFHlBAX/b9JTy+zjqXKm6j/qjGHG6cRA4vd/ZvrteFqW7+LbIKRDhA6U8GioUaq7V' >> ~/.ssh/known_hosts
          echo 'codeserver.dev.51b73c1d-15ea-4605-9b35-139337cefb1f.drush.in ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw5AjaS6bU+BxtOvbbSwx3pC0GcJmKaCkYep2WUSSL1vcwyyFBVwdukTP18ysj6huuxnMWNwPLqJSWT4jI6cbUZWf7bWVRFIZJ+0JXv3pRfJKT+mOLk4xhPHvt5idh4rU63dJRJjLodJpaS48gfTdPxt4KZPm/Y76KCDAMD++K0Itd9G/Aily7miaPXTBcx7ioobwhRBiJxJSyQoSolXrIpN7dgw7Kih1HLIsAj+iChHOtL7NCsK8+xYrUCCdAH/7ldKz4opgx+FY3tTHrgvZtFHlBAX/b9JTy+zjqXKm6j/qjGHG6cRA4vd/ZvrteFqW7+LbIKRDhA6U8GioUaq7V' >> ~/.ssh/known_hosts
          git remote add pantheon ssh://codeserver.dev.51b73c1d-15ea-4605-9b35-139337cefb1f@codeserver.dev.51b73c1d-15ea-4605-9b35-139337cefb1f.drush.in:2222/~/repository.git
          git push pantheon $CIRCLE_BRANCH:master --force
          sleep 25
          bash diffy-utils/runCheck.sh $CIRCLE_SHA1 $API_KEY

workflows:
  version: 2
  build-deploy:
    jobs:
      - display_branch
      - pr:
          filters:
            branches:
              ignore:
                - master
                - staging
                - /release-.*/
