<?php

/**
 * @file
 * Contains diffy_try.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function diffy_try_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the diffy_try module.
    case 'help.page.diffy_try':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Try out Diffy screenshots') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function diffy_try_theme($existing, $type, $theme, $path) {
  return [
    'diffy_try_collect_url' => [
      'render element' => 'form',
      'template' => 'diffy-try-collect-url-form',
    ],
    'diffy_compare_two_urls' => [
      'render element' => 'form',
      'template' => 'diffy-compare-two-urls-form',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function diffy_try_mail($key, &$message, $params) {
$options = array(
  'langcode' => $message['langcode'],
);

 switch ($key) {
   case 'compare_sites':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('Request to compare from @email', array('@email' => $params['email']), $options);
     $message['body'][] = $params['message'];
     break;
 }
}
